[package]
name = "host"
version.workspace = true
edition.workspace = true

[dependencies]
methods = { workspace = true }
risc0-zkvm = { workspace = true, features = ["client"] }
serde = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
