[package]
name = "verify-full"
version.workspace = true
edition.workspace = true

[dependencies]
fixtures = { workspace = true }
serde_json = { workspace = true }
verity-tls = { workspace = true, features = [
  "private-facets",
  "public-facets",
] }
